OW_Movement_Pointers: ;$61602
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $A1, $5A, $AE, $5A, $B8, $5A, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $C3, $5A
	db $12, $5B, $D8, $5A, $FA, $5A, $CD, $5A
	db $FF, $FF, $18, $5B, $FF, $FF, $FF, $FF
	db $FF, $FF, $1E, $5B, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $3A, $5A
	db $65, $5B, $72, $5B, $65, $5B, $FF, $FF
	db $8C, $5B, $7F, $5B, $FF, $FF, $9C, $5B
	db $FF, $FF, $94, $5B, $FF, $FF, $FF, $FF
	db $CA, $5B, $FF, $FF, $B3, $5B, $D3, $5B
	db $FF, $FF, $E0, $5B, $FF, $FF, $E0, $5B
	db $FF, $FF, $FF, $FF, $06, $5C, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $54, $5A, $E9, $5B, $36, $5C
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $7F, $5A, $40, $5A, $3A, $5C, $FF, $FF
	db $FF, $FF, $FF, $FF, $99, $5A, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $4D, $5A, $78, $5A, $FF, $FF, $66, $5A
	db $FF, $FF, $86, $5A, $FF, $FF, $FF, $FF
	db $58, $5B, $40, $5B, $3D, $5A, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $C3, $5A
	db $FF, $FF, $1E, $5B, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $3A, $5A
	db $FF, $FF, $94, $5B, $FF, $FF, $FF, $FF
	db $FF, $FF, $E0, $5B, $FF, $FF, $E0, $5B
	db $FF, $FF, $FF, $FF, $06, $5C, $FF, $FF
	db $8E, $5C, $9C, $5C, $FF, $FF, $A8, $5C
	db $87, $5C, $EA, $5C, $FF, $FF, $FF, $FF
	db $FF, $FF, $95, $5C, $80, $5C, $FF, $FF
	db $FF, $FF, $BE, $5C, $B3, $5C, $FF, $FF
	db $C5, $5C, $FF, $FF, $FF, $FF, $FF, $FF
	db $A2, $5C, $FF, $FF, $E4, $5C, $FF, $FF
	db $F0, $5C, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FE, $5C, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $08, $5D, $FF, $FF
	db $FF, $FF, $12, $5D, $FF, $FF, $0D, $5D
	db $1A, $5D, $FF, $FF, $22, $5D, $FF, $FF
	db $FF, $FF, $29, $5D, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $30, $5D
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $3D, $5D, $FF, $FF
	db $FF, $FF, $FF, $FF, $59, $5D, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $63, $5D
	db $73, $5D, $FF, $FF, $FF, $FF, $FF, $FF
	db $7B, $5D, $77, $5D, $FF, $FF, $77, $5D
	db $8D, $5D, $84, $5D, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $9D, $5D, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $D1, $5D, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $DD, $5D
	db $FF, $FF, $FF, $FF, $C8, $5D, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $E6, $5D, $02, $5E
	db $FF, $FF, $FF, $FF, $FF, $FF, $EE, $5D
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $F6, $5D, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $0E, $5E, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $1F, $5E, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $2A, $5E
	db $53, $5E, $FF, $FF, $53, $5E, $FF, $FF
	db $FF, $FF, $3A, $5E, $FF, $FF, $49, $5E
	db $FF, $FF, $FF, $FF, $4E, $5E, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $5F, $5E
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $76, $5E, $FF, $FF
	db $FF, $FF, $FF, $FF, $86, $5E, $7E, $5E
	db $FF, $FF, $FF, $FF, $95, $5E, $8E, $5E
	db $FF, $FF, $FF, $FF, $FF, $FF, $9F, $5E
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $A9, $5E, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $57, $5C, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $6A, $5E, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $70, $5E, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $08, $5E
	db $FF, $FF, $FF, $FF, $FF, $FF, $DD, $5D
	db $FF, $FF, $FF, $FF, $AD, $5D, $FF, $FF
	db $BC, $5D, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $AC, $5E, $D1, $5E, $FF, $FF, $FF, $FF
	db $B6, $5E, $B1, $5E, $FF, $FF, $FF, $FF
	db $C0, $5E, $BB, $5E, $FF, $FF, $FF, $FF
	db $FF, $FF, $C5, $5E, $FF, $FF, $FF, $FF
	db $CA, $5E, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $4E, $5D, $FF, $FF, $FF, $FF, $4E, $5D
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $28, $00, $18, $24, $00, $06
	